### ISSUE TITLE
Challenges of a inactive people should still be accessible to admins

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1220]
Currently, an admin cannot access challenges of inactive people. An admin should always have edit and view access to all challenges, also those of inactive people and archived challenges (of inactive people).

Note that this does not apply to content owners and view only roles. They should never have edit access to challenges.

**Comment by SimonLab** [comment]
@asimonw I think Admin now can see and edit any challenges (published, archived linked to active or inactive user), this might have been fixed with another PR, or did I miss something?

For `content owner` and `view only` they can't edit any challenges but can they view any challenges (archive/publish on active/inactive user)?

**Comment by asimonw** [comment]
@SimonLab I'm currently logged in as an admin. I've disabled Charcoal and can now no longer access Challenge number 6. It still appears in the list, but I get a 404 when I try to access it.

**Comment by SimonLab** [comment]
When a user is disable directly the challenges are still accessible for admin, however when an organisation is disable (which disable the users of the organisation) the challenges are not accessble anymore.

@asimonw thanks for confirming this. For content owner and view only they can view any challenges but can't edit them is this right (sorry to ask again not sure if you saw my previous question)?

**Comment by asimonw** [comment]
Oh that could be. Still testing this. 

Yes, in principle content owners and view only shouldn't see archived challenges. But it's not crucial for now. So it it's simpler to give them view (but no edit) access to all challenges, that's ok.

**Comment by asimonw** [comment]
@SimonLab Do you still need more info on this?

**Comment by SimonLab** [comment]
@asimonw I think it's ok thanks, I'm doing more test to catch the edges case and to find out why the disable org change the logic compare to disable user

**Comment by SimonLab** [comment]
The issues is in the query of the challenge plugin:
```
    'WHERE organisations.active = true',
    'AND challenges.id = ' + challengeId + ';'
```
The condition which check the organistaion is active is not necessary
